SELECT NRROM,
       CODCLI,
	   'CLIENTE'   = (SELECT A1_NOME FROM SA1010 WHERE A1_COD = [CODCLI] AND D_E_L_E_T_ = ''),
	   'CODTRANSP' = (SELECT ZZQ_TRANSP FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
	   'TRANSP'    = (SELECT ZZQ_DESTRA FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
	   'VEICULO'   = (SELECT ZZQ_DESVEI FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
       EMISDF,
       CDESP,
       NRDF,
	   SERDF,
	   VLDF,
       DTEMIS,
       NRDC,
       TPDC,
       SERDC,
       EMISDC,
	   CASE EMISDC
			WHEN '000000376' THEN 'SOBEL'
			WHEN '000000146' THEN 'JMT'
			WHEN '000002496' THEN '3F'
			ELSE ''
		END AS EMISSOR,
			   CASE
			WHEN (SELECT C5_NUM FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_NUM FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_NUM FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			ELSE ''
	   END AS NRPV,
	  CASE
			WHEN (SELECT C5_ZZTIPO FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_ZZTIPO FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_ZZTIPO FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			ELSE ''
	   END AS TPPV
FROM(
SELECT GW4_EMISDF AS 'EMISDF',
	   GW4_CDESP  AS 'CDESP',
	   GW4_SERDF  AS 'SERDF',
	   GW4_NRDF	  AS 'NRDF',
	   GW4_DTEMIS AS 'DTEMIS',
	   GW4_NRDC	  AS 'NRDC',
	   GW4_TPDC	  AS 'TPDC',
	   GW4_SERDC  AS 'SERDC',
	   GW4_EMISDC AS 'EMISDC',
       (SELECT GW1_NRROM FROM GW1010 WHERE GW1_NRDC = GW4_NRDC AND GW1_SERDC = GW4_SERDC AND GW1_EMISDC = GW4_EMISDC AND D_E_L_E_T_ = '' ) AS 'NRROM',
	   CASE 
			WHEN (SELECT F2_CLIENTE FROM SF2010 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_CLIENTE FROM SF2010 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_CLIENTE FROM SF2020 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_CLIENTE FROM SF2020 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_CLIENTE FROM SF2040 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_CLIENTE FROM SF2040 WHERE F2_DOC = GW4_NRDC AND F2_SERIE = GW4_SERDC AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS CODCLI,
	   CASE 
		 WHEN (GW3S.GW3_VLDF) IS NOT NULL THEN (GW3S.GW3_VLDF)
		 WHEN (GW3J.GW3_VLDF) IS NOT NULL THEN (GW3J.GW3_VLDF)
		 WHEN (GW33.GW3_VLDF) IS NOT NULL THEN (GW33.GW3_VLDF)
		 ELSE NULL
       END AS 'VLDF'	   
FROM GW4010 GW4 
LEFT JOIN GW3010 GW3S ON GW3S.GW3_NRDF = GW4.GW4_NRDF AND GW3S.GW3_SERDF = GW4.GW4_SERDF AND GW4.GW4_EMISDF = GW3S.GW3_EMISDF AND GW3S.D_E_L_E_T_ = ''
LEFT JOIN GW3020 GW3J ON GW3J.GW3_NRDF = GW4.GW4_NRDF AND GW3J.GW3_SERDF = GW4.GW4_SERDF AND GW4.GW4_EMISDF = GW3J.GW3_EMISDF AND GW3J.D_E_L_E_T_ = ''
LEFT JOIN GW3040 GW33 ON GW33.GW3_NRDF = GW4.GW4_NRDF AND GW33.GW3_SERDF = GW4.GW4_SERDF AND GW4.GW4_EMISDF = GW33.GW3_EMISDF AND GW33.D_E_L_E_T_ = ''
WHERE GW4_NRDC IN        ( SELECT F2_DOC 
                           FROM SF2040 
                           WHERE F2_EMISSAO BETWEEN '20210101' AND '20210228'
						   AND F2_SERIE = GW4.GW4_SERDC
                           AND D_E_L_E_T_ = ''                           
                           AND F2_ROMANEI <> ''

						   UNION ALL

						   SELECT F2_DOC 
                           FROM SF2020 
                           WHERE F2_EMISSAO BETWEEN '20210101' AND '20210228'
                           AND D_E_L_E_T_ = ''      
						   AND F2_SERIE = GW4.GW4_SERDC
                           AND F2_ROMANEI <> ''

						   UNION ALL 

						   SELECT F2_DOC 
                           FROM SF2010 
                           WHERE F2_EMISSAO BETWEEN '20210101' AND '20210228'
                           AND D_E_L_E_T_ = ''      
						   AND F2_SERIE = GW4.GW4_SERDC
                           AND F2_ROMANEI <> ''
						   )
AND GW4.D_E_L_E_T_  = ''
) AS RES







