DECLARE @DTINI AS VARCHAR(8),
        @DTFIN AS VARCHAR(8),
		@NRROM AS VARCHAR(MAX)

SET @DTINI = '20210201'
SET @DTFIN = '20210201'
  
SELECT NRROM,
       NUMNFROM,
	   CODCLI,
	   'CLIENTE'   = (SELECT A1_NOME FROM SA1010 WHERE A1_COD = [CODCLI] AND D_E_L_E_T_ = ''),
	   'CODTRANSP' = (SELECT ZZQ_TRANSP FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
	   'TRANSP'    = (SELECT ZZQ_DESTRA FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
	   'VEICULO'   = (SELECT ZZQ_DESVEI FROM ZZQ010 WHERE ZZQ_ROMANE = SUBSTRING([NRROM],1,6) AND D_E_L_E_T_ = ''),
	   TPDOCF, 
	   CODEMIT,
	   CASE CODEMIT
			WHEN '000000376' THEN 'SOBEL'
			WHEN '000000146' THEN 'JMT'
			WHEN '000002496' THEN '3F'
			ELSE ''
		END AS EMIT,
	   CASE
			WHEN (SELECT C5_NUM FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_NUM FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_NUM FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_NUM FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			ELSE ''
	   END AS NRPV,
	  CASE
			WHEN (SELECT C5_ZZTIPO FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5010 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_ZZTIPO FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5020 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN (SELECT C5_ZZTIPO FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT C5_ZZTIPO FROM SC5040 WHERE C5_NOTA = [NRDC] AND C5_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			ELSE ''
	   END AS TPPV,
	   NRDC,
	   SERDC,
	   VALCARGANF,
	   CONVERT(VARCHAR,CAST(DTEMISNFE AS DATETIME),103) AS DTEMISNFE,
	   PESBRUTO,
	   QTVOL,
	   'MUNICIO'  = (SELECT A1_MUN FROM SA1010 WHERE A1_COD = [CODCLI] AND D_E_L_E_T_ = '') ,
	   'UF'       = (SELECT A1_EST FROM SA1010 WHERE A1_COD = [CODCLI] AND D_E_L_E_T_ = ''),
	   TPDF,
	   TIPO,
	   VLCALCFRET,
	   NRDF,
	   TAXAS,
	   VLIMP,
	   PEDAG,
	   VLFATFRETE,
	   NRDOCFAT,
	   CONVERT(VARCHAR,CAST(
	   (CASE 
			WHEN  (SELECT TOP 1 E1_VENCREA FROM SE1010 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT TOP 1 E1_VENCREA FROM SE1010 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN  (SELECT TOP 1 E1_VENCREA FROM SE1020 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT TOP 1 E1_VENCREA FROM SE1020 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			WHEN  (SELECT TOP 1 E1_VENCREA FROM SE1040 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT TOP 1 E1_VENCREA FROM SE1040 WHERE E1_NUM =[NRDC] AND E1_SERIE = [SERDC] AND D_E_L_E_T_ = '')
			ELSE ''
		END) AS DATETIME), 103) AS VECTOTITULO
FROM(
SELECT NRROM,
       NUMNFROM,
	   CODEMIT,
	   CASE 
			WHEN (SELECT F2_CLIENTE FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_CLIENTE FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_CLIENTE FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_CLIENTE FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_CLIENTE FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_CLIENTE FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS CODCLI,
	   CASE 
			WHEN (SELECT F2_EMISSAO FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_EMISSAO FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_EMISSAO FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_EMISSAO FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_EMISSAO FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_EMISSAO FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS DTEMISNFE,
	   CASE 
			WHEN (SELECT F2_PBRUTO FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_PBRUTO FROM SF2010 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_PBRUTO FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_PBRUTO FROM SF2020 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_PBRUTO FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT  F2_PBRUTO FROM SF2040 WHERE F2_DOC = [NRDC] AND F2_SERIE = [SERDC]AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS PESBRUTO,
       TPDOCF,
	   NRDC,
	   QTVOL,
	   SERDC,
	   CASE [TPDF]
		WHEN  '1' THEN 'NORMAL'
		WHEN  '2' THEN 'COMPLEMENTO VALOR'
		WHEN  '3' THEN 'COMPLEMENTO IMPOSTO'
		WHEN  '4' THEN 'REINTREGA'
		WHEN  '5' THEN 'DEVOLUÇÃO'
		WHEN  '6' THEN 'REDESPACHO'
		WHEN  '7' THEN 'SERVIÇO'
	   END AS TPDF,
       VLCALCFRET,
	   NRDF,
	   VALCARGANF,
	   VLFATFRETE,
	   TAXAS,
	   PEDAG,
	   CASE
			WHEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4010 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4010 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '') 
			WHEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4020 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4020 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '')
			WHEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4040 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '') IS NOT NULL THEN (SELECT COUNT(GW4_NRDC) AS TOTALDOCS FROM GW4040 WHERE GW4_NRDF = [NRDF] AND D_E_L_E_T_ = '') 
	   END AS NRDOCFAT,
	   TIPO,
	   VLIMP
FROM(
SELECT NRROM,
       NRDC,
       VLCALCFRET,
	   NRDF,
	   CODEMIT,
	   VALCARGANF,
	   SERDC,
	   QTVOL,
	   'NUMNFROM' =  (SELECT COUNT(GW1_NRDC) FROM GW1010 WHERE GW1_NRROM IN ([NRROM]) AND D_E_L_E_T_ = ''),
	   CASE 
			WHEN (SELECT GW3_VLDF FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLDF FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_VLDF FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLDF FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_VLDF FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLDF FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS VLFATFRETE,
	   TIPO,
	    CASE 
			WHEN (SELECT GW3_CDESP FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_CDESP FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_CDESP FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_CDESP FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_CDESP FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_CDESP FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS TPDOCF,
	   CASE 
			WHEN (SELECT GW3_TPDF  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TPDF  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_TPDF  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TPDF  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_TPDF  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TPDF  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS TPDF,
	   CASE 
			WHEN (SELECT GW3_TAXAS  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TAXAS  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_TAXAS  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TAXAS  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_TAXAS  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_TAXAS  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS TAXAS,
	   CASE 
			WHEN (SELECT GW3_VLIMP  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLIMP  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_VLIMP  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLIMP  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_VLIMP  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_VLIMP  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS VLIMP,
	   CASE 
			WHEN (SELECT GW3_PEDAG  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_PEDAG  FROM GW3010 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_PEDAG  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_PEDAG  FROM GW3020 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			WHEN (SELECT GW3_PEDAG  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_SERDF = [SERIEDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT GW3_PEDAG  FROM GW3040 WHERE GW3_NRDF = [NRDF] AND GW3_CDREM = [CDREM] AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS PEDAG
FROM(
SELECT DISTINCT GWF_NRROM AS NRROM,
       GW1.GW1_NRDC       AS NRDC,	   
	   GW1_QTVOL          AS QTVOL,
	   GW1_CDREM          AS CDREM ,
	   GW1.GW1_SERDC      AS SERDC,
	   GW1_EMISDC         AS CODEMIT,
       GWI_VLFRET         AS VLCALCFRET,
	   GWF_NRDF           AS NRDF,	   
	   GWF_SERDF          AS SERIEDF,
	     CASE 
			WHEN (SELECT F2_VALBRUT FROM SF2010 WHERE F2_DOC = GW1_NRDC AND F2_SERIE = GW1_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_VALBRUT FROM SF2010 WHERE F2_DOC = GW1_NRDC AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_VALBRUT FROM SF2020 WHERE F2_DOC = GW1_NRDC AND F2_SERIE = GW1_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_VALBRUT FROM SF2020 WHERE F2_DOC = GW1_NRDC AND D_E_L_E_T_ = '')
			WHEN (SELECT F2_VALBRUT FROM SF2040 WHERE F2_DOC = GW1_NRDC AND F2_SERIE = GW1_SERDC AND D_E_L_E_T_ = '') IS NOT NULL THEN  (SELECT F2_VALBRUT FROM SF2040 WHERE F2_DOC = GW1_NRDC AND D_E_L_E_T_ = '')
			ELSE NULL
	   END AS VALCARGANF,
	   GWI_CDCOMP AS 'TIPO'
FROM GWI010 GWI
LEFT JOIN GWF010 GWF   ON GWF.GWF_NRCALC   = GWI.GWI_NRCALC
LEFT JOIN GW1010 GW1   ON GW1.GW1_NRROM    = GWF.GWF_NRROM 
LEFT JOIN GWN010 GWN   ON GWN.GWN_NRROM    = GWF.GWF_NRROM
WHERE GWI_NRCALC IN (SELECT GWF_NRCALC
                     FROM GWF010 
                     WHERE GWF_NRROM IN ('20358401')
                     AND D_E_L_E_T_ = '') 
AND GWI.GWI_VLFRET <> 0					 
AND GWI.D_E_L_E_T_ = ''
AND GWF.D_E_L_E_T_ = ''
AND GW1.D_E_L_E_T_ = '' 
AND GWN.D_E_L_E_T_ = ''
) AS RESULT
) AS RES
) AS R
ORDER BY NRROM,
         NRDF		



SELECT *
FROM ZZQ010 
WHERE ZZQ_ROMANE = '203776'



SELECT GW3_ORIDTE, *
FROM GW3040
WHERE GW3_NRDF IN (SELECT GW4_NRDF
                    FROM GW4010 
                    WHERE GW4_NRDC IN (SELECT GW1_NRDC FROM GW1010 WHERE GW1_NRROM = '20358401' AND D_E_L_E_T_ = '')
                   AND D_E_L_E_T_ = '')
AND D_E_L_E_T_ = ''


SELECT *
FROM GW4010 
WHERE GW4_NRDC IN ('128219', '128220')
AND D_E_L_E_T_ = ''

SELECT GW3_NRFAT, *
FROM GW3040 
WHERE GW3_NRDF IN ('000000613', '000000614')
AND D_E_L_E_T_ = ''

SELECT *
FROM GWN010 
WHERE GWN_NRROM = '20358401' 
AND D_E_L_E_T_ = ''


SELECT *
FROM GW6040
WHERE GW6_NRFAT IN ('613 ',            
                    '614D',            
                    '614 ')
AND D_E_L_E_T_ = ''					




SELECT *
FROM GW4010 
WHERE GW4_NRDC IN (SELECT GW1_NRDC FROM GW1010 WHERE GW1_NRROM = '20358401' AND D_E_L_E_T_ = '')
AND D_E_L_E_T_ = ''


SELECT DISTINCT EMISSAO 
FROM(
SELECT F2_EMISSAO AS EMISSAO
FROM SF2010 
WHERE F2_ROMANEI = '203776' 
AND D_E_L_E_T_  = ''

UNION ALL

SELECT F2_EMISSAO 
FROM SF2020 
WHERE F2_ROMANEI = '203776' 
AND D_E_L_E_T_  = ''

UNION ALL

SELECT F2_EMISSAO 
FROM SF2040 
WHERE F2_ROMANEI = '203776' 
AND D_E_L_E_T_  = ''
) AS RES



