DECLARE @DTINI AS VARCHAR(8),
        @DTFIN AS VARCHAR(8)

SET @DTINI = '20210301'
SET @DTFIN = '20210430'

SELECT	  'TP' = 'PVS',
          CASE C5_ZZTIPO 
				WHEN 'N' THEN 'NORMAL'
				WHEN 'F' THEN 'BONIFICACAO'
				WHEN 'X' THEN 'BONIFICACAO'
				WHEN 'L' THEN 'PALETE'
				ELSE ''  
			END               AS 'TIPO', 	
			
         D2_COD AS 'COD.PRD', 
		 B1_DESC AS 'DESC', 
		 B1_ZZFAMIL AS 'FAM', 
		'FAMILIA'      = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z6' AND X5_CHAVE = B1_XFAMILI),
		'MARCA'        = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z8' AND X5_CHAVE = B1_XMARCA),
		'CATEGORIA'    = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z9' AND X5_CHAVE = B1_XCATEGO),
		'SUBCATEGORIA' = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z4' AND X5_CHAVE = B1_XSUBCAT),
          C6_PRODUTO          AS 'PRODUTO', 
          C6_DESCRI           AS 'DESCRICAO', 
		  B1_ZZFAMIL          AS 'FAMILIA', 
		  C5_NUM              AS 'NUM.PEDIDO', 
		  C5_ROMANEI          AS 'ROMANEIO',
		  D2_DOC            AS 'NF',
--		  C5_EMISSAO          AS 'EMISSAO', 
		  CAST(CONVERT (VARCHAR(10), C5_EMISSAO, 103) AS DATE) AS 'EMISSAO',
--          C5_FECENT           AS 'ENTREGA',
          CAST(CONVERT (VARCHAR(10), C5_FECENT, 103) AS DATE) AS 'ENTREGA',
		  C6_ITEM             AS 'ITEM', 
--		  C6_QTDVEN-C6_QTDENT AS 'SALDO',
		  C5_CLIENTE          AS 'COD.CLIENTE', 
		  A1_NOME             AS 'CLIENTE',
		  A1_ZZREDE           AS 'REDE',
		  A1_EST              AS 'ESTADO', 
		  A1_MUN              AS 'MUNICIPIO',
		  C5_VEND1            AS 'COD.VEND',     
		  A3_NOME             AS 'VENDEDOR',
		  A3_SUPER            AS 'COD.SUPER',  
		  'SUPERVISOR' = (SELECT A3_NOME FROM SA3010 WHERE A3_COD = (SELECT A3_SUPER FROM SA3010 WHERE A3_COD = A1_VEND AND D_E_L_E_T_ = '') AND D_E_L_E_T_ = ''), 
		  	'TP.FRETE.PV' = CASE A1_TPFRET  
			          WHEN 'C' THEN 'CIF'
					  WHEN 'F' THEN 'FOB'
                      ELSE ''
                     END, 
--		  C9_QTDLIB           AS 'RESERVA',
		  CASE C5_STAPED 
			WHEN 'S' THEN 'BLOQUEIO COMERCIAL'
			WHEN 'M' THEN 'MARGEM'
			WHEN 'C' THEN 'CREDITO'
			WHEN 'A' THEN 'AGENDAR'
			WHEN 'P' THEN 'PALETE'
			WHEN 'O' THEN 'OUTROS'
			WHEN 'R' THEN 'REJEITADO CREDITO'
			WHEN 'L' THEN 'ADM.PEDIDO'
			WHEN 'D' THEN 'LIB P/ GERAR ROM'
			WHEN 'T' THEN 'EM ROMANEIO'
			WHEN 'F' THEN 'FATURADO'
			ELSE ''
			END AS 'STATUS',
			A1_ZZROTA         AS 'ROTA',
		   (B1_PESO * C6_QTDVEN)   AS 'PESO.LIQUIDO',
		   (B1_PESBRU * C6_QTDVEN) AS 'PESO.BRUTO',
		    ZZQ_DESVEI AS 'TP.VEICULO',
			C5_ZZOBS1  AS 'OBS.PEDIDO',
		    A1_ZZOBSER AS 'OBS.SOBEL', 
		    A1_OBSERV  AS 'OBS.PROTHEUS',
			A1_REQAGEN AS 'REQ.AGENDA',
			--C5_DTAGEN  AS 'DT.AGENDAMENTO 1',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN, 103) AS DATE) AS 'DT.AGENDAMENTO 1',
		    C5_HRAGEN  AS 'HORA.AGENDAMENTO 1',
		   -- C5_DTAGEN1 AS 'DT.AGENDAMENTO 2',
		    CAST(CONVERT (VARCHAR(10), C5_DTAGEN1, 103) AS DATE) AS 'DT.AGENDAMENTO 2',
		    C5_HRAGEN2 AS 'HORA.AGENDAMENTO 2',		  
			--C5_DTAGEN2 AS 'DT.AGENDAMENTO 3',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN2, 103) AS DATE) AS 'DT.AGENDAMENTO 3',
		    C5_HRAGEN3 AS 'HORA.AGENDAMENTO 3',
			--C9_DTCARRE AS 'DT.CARREGAMENTO',
			CAST(CONVERT (VARCHAR(10), ZZQ_DTCARR, 103) AS DATE) AS 'DT.CARREGAMENTO',
			C5_TRANSP  AS 'TRANSP. ROMANEIO',
			'DESCRICAO. TRANSP.ROMANEIO' = ZZQ_DESTRA,
			'TIPO.VEICULO' = ZZQ_DESVEI,
			'TIPO.CARGA'   = IIF(ZZQ_TPCARG = '1', 'BATIDO', 'PALETIZADO'),
			'PRC.VENDA'    = C6_PRCVEN,
			'TP.FRETE.PV' = CASE C5_TPFRETE 
			                  WHEN 'C' THEN 'CIF'
							  WHEN 'F' THEN 'FOB'
                              ELSE ''
                             END, 
			'PED.CLIENTE'  = C5_ZZPEDCL,
			'HRA.ENTREGA'  = A1_ZZHORA,
			'LOJA.REDE'    = A1_ZZLOJA
 FROM SC5010 C5  
 LEFT JOIN SC6010 AS SC6 ON C6_NUM = C5_NUM AND C6_CLI = C5_CLIENT AND C6_LOJA = C5_LOJACLI AND SC6.D_E_L_E_T_ = ' '  
 LEFT JOIN SA1010 AS SA1 ON A1_COD = C5_CLIENT AND A1_LOJA = C5_LOJACLI AND SA1.D_E_L_E_T_ = ' '  
 LEFT JOIN SB1010 AS SB1 ON B1_COD = C6_PRODUTO AND SB1.D_E_L_E_T_ = ' '  
 LEFT JOIN SA3010 AS SA3 ON A3_COD = C5_VEND1 AND SA3.D_E_L_E_T_ = ' ' 
 LEFT JOIN SC9010 AS SC9 ON C9_PEDIDO = SC6.C6_NUM AND C9_ITEM = SC6.C6_ITEM AND C9_PRODUTO = SC6.C6_PRODUTO AND SC9.D_E_L_E_T_ = ' ' AND C9_BLEST 	= '' AND C9_BLCRED = ''  
 LEFT JOIN ZZQ010 AS ZZQ ON C5_ROMANEI = ZZQ_ROMANE AND ZZQ.D_E_L_E_T_ = ' ' 
 LEFT JOIN SD2010 AS SD2 ON SD2.D2_DOC = SC6.C6_NOTA AND SD2.D2_SERIE = SC6.C6_SERIE AND SD2.D_E_L_E_T_ = ''
 WHERE 
 --AND C6_NOTA = ''   
 --AND C5_EMISSAO BETWEEN (SELECT CONVERT(VARCHAR,CAST(GETDATE() - 180 AS DATE),112)) AND (SELECT CONVERT(VARCHAR,CAST(GETDATE() AS DATE),112)) 
  C5_EMISSAO BETWEEN  @DTINI AND @DTFIN
 AND C5_CLIENTE NOT IN ('002268' , '015699', '005286' )
 AND C6_PRODUTO <> 'VERBA'     
 AND C6_PRODUTO <> '1000.00.00001'                   
 AND C5_ZZTIPO IN ('N','F','X', 'L') 
 AND C6_BLQ <> 'R'
 AND B1_TIPO IN ('PA','RV') 
 AND C5.D_E_L_E_T_ = '' 

 UNION ALL

SELECT	  'TP' = 'PVJ',
          CASE C5_ZZTIPO 
				WHEN 'N' THEN 'NORMAL'
				WHEN 'F' THEN 'BONIFICACAO'
				WHEN 'X' THEN 'BONIFICACAO'
				WHEN 'L' THEN 'PALETE'
				ELSE ''  
			END               AS 'TIPO',
		 D2_COD AS 'COD.PRD', 
		 B1_DESC AS 'DESC', 
		 B1_ZZFAMIL AS 'FAM', 
		'FAMILIA'      = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z6' AND X5_CHAVE = B1_XFAMILI),
		'MARCA'        = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z8' AND X5_CHAVE = B1_XMARCA),
		'CATEGORIA'    = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z9' AND X5_CHAVE = B1_XCATEGO),
		'SUBCATEGORIA' = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z4' AND X5_CHAVE = B1_XSUBCAT),
          C6_PRODUTO          AS 'PRODUTO', 
          C6_DESCRI           AS 'DESCRICAO', 
		  B1_ZZFAMIL          AS 'FAMILIA', 
		  C5_NUM              AS 'NUM.PEDIDO', 
		  C5_ROMANEI          AS 'ROMANEIO',
		  D2_DOC            AS 'NF',
--		  C5_EMISSAO          AS 'EMISSAO', 
		  CAST(CONVERT (VARCHAR(10), C5_EMISSAO, 103) AS DATE) AS 'EMISSAO',
--          C5_FECENT           AS 'ENTREGA',
          CAST(CONVERT (VARCHAR(10), C5_FECENT, 103) AS DATE) AS 'ENTREGA',
		  C6_ITEM             AS 'ITEM', 
--		  C6_QTDVEN-C6_QTDENT AS 'SALDO',
		  C5_CLIENTE          AS 'COD.CLIENTE', 
		  A1_NOME             AS 'CLIENTE',
		  A1_ZZREDE           AS 'REDE',
		  A1_EST              AS 'ESTADO', 
		  A1_MUN              AS 'MUNICIPIO',
		  C5_VEND1            AS 'COD.VEND',     
		  A3_NOME             AS 'VENDEDOR',
		  A3_SUPER            AS 'COD.SUPER',  
		  'SUPERVISOR' = (SELECT A3_NOME FROM SA3010 WHERE A3_COD = (SELECT A3_SUPER FROM SA3010 WHERE A3_COD = A1_VEND AND D_E_L_E_T_ = '') AND D_E_L_E_T_ = ''), 
		  	'TP.FRETE.PV' = CASE A1_TPFRET  
			          WHEN 'C' THEN 'CIF'
					  WHEN 'F' THEN 'FOB'
                      ELSE ''
                     END, 
--		  C9_QTDLIB           AS 'RESERVA',
		  CASE C5_STAPED 
			WHEN 'S' THEN 'BLOQUEIO COMERCIAL'
			WHEN 'M' THEN 'MARGEM'
			WHEN 'C' THEN 'CREDITO'
			WHEN 'A' THEN 'AGENDAR'
			WHEN 'P' THEN 'PALETE'
			WHEN 'O' THEN 'OUTROS'
			WHEN 'R' THEN 'REJEITADO CREDITO'
			WHEN 'L' THEN 'ADM.PEDIDO'
			WHEN 'D' THEN 'LIB P/ GERAR ROM'
			WHEN 'T' THEN 'EM ROMANEIO'
			WHEN 'F' THEN 'FATURADO'
			ELSE ''
			END AS 'STATUS',
			A1_ZZROTA         AS 'ROTA',
		   (B1_PESO * C6_QTDVEN)   AS 'PESO.LIQUIDO',
		   (B1_PESBRU * C6_QTDVEN) AS 'PESO.BRUTO',
		    ZZQ_DESVEI AS 'TP.VEICULO',
			C5_ZZOBS1  AS 'OBS.PEDIDO',
		    A1_ZZOBSER AS 'OBS.SOBEL', 
		    A1_OBSERV  AS 'OBS.PROTHEUS',
			A1_REQAGEN AS 'REQ.AGENDA',
			--C5_DTAGEN  AS 'DT.AGENDAMENTO 1',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN, 103) AS DATE) AS 'DT.AGENDAMENTO 1',
		    C5_HRAGEN  AS 'HORA.AGENDAMENTO 1',
		   -- C5_DTAGEN1 AS 'DT.AGENDAMENTO 2',
		    CAST(CONVERT (VARCHAR(10), C5_DTAGEN1, 103) AS DATE) AS 'DT.AGENDAMENTO 2',
		    C5_HRAGEN2 AS 'HORA.AGENDAMENTO 2',		  
			--C5_DTAGEN2 AS 'DT.AGENDAMENTO 3',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN2, 103) AS DATE) AS 'DT.AGENDAMENTO 3',
		    C5_HRAGEN3 AS 'HORA.AGENDAMENTO 3',
			--C9_DTCARRE AS 'DT.CARREGAMENTO',
			CAST(CONVERT (VARCHAR(10), ZZQ_DTCARR, 103) AS DATE) AS 'DT.CARREGAMENTO',
			C5_TRANSP  AS 'TRANSP. ROMANEIO',
			'DESCRICAO. TRANSP.ROMANEIO' = ZZQ_DESTRA,
			'TIPO.VEICULO' = ZZQ_DESVEI,
			'TIPO.CARGA'   = IIF(ZZQ_TPCARG = '1', 'BATIDO', 'PALETIZADO'),
			'PRC.VENDA'    = C6_PRCVEN,
			'TP.FRETE.PV' = CASE C5_TPFRETE 
			                  WHEN 'C' THEN 'CIF'
							  WHEN 'F' THEN 'FOB'
                              ELSE ''
                             END, 
			'PED.CLIENTE'  = C5_ZZPEDCL,
			'HRA.ENTREGA'  = A1_ZZHORA,
			'LOJA.REDE'    = A1_ZZLOJA
 FROM SC5020 C5  
 LEFT JOIN SC6020 AS SC6 ON C6_NUM = C5_NUM AND C6_CLI = C5_CLIENT AND C6_LOJA = C5_LOJACLI AND SC6.D_E_L_E_T_ = ' '  
 LEFT JOIN SA1010 AS SA1 ON A1_COD = C5_CLIENT AND A1_LOJA = C5_LOJACLI AND SA1.D_E_L_E_T_ = ' '  
 LEFT JOIN SB1020 AS SB1 ON B1_COD = C6_PRODUTO AND SB1.D_E_L_E_T_ = ' '  
 LEFT JOIN SA3010 AS SA3 ON A3_COD = C5_VEND1 AND SA3.D_E_L_E_T_ = ' ' 
 LEFT JOIN SC9020 AS SC9 ON C9_PEDIDO = SC6.C6_NUM AND C9_ITEM = SC6.C6_ITEM AND C9_PRODUTO = SC6.C6_PRODUTO AND SC9.D_E_L_E_T_ = ' ' AND C9_BLEST 	= '' AND C9_BLCRED = ''  
 LEFT JOIN ZZQ010 AS ZZQ ON C5_ROMANEI = ZZQ_ROMANE AND ZZQ.D_E_L_E_T_ = ' ' 
 LEFT JOIN SD2020 AS SD2 ON SD2.D2_DOC = SC6.C6_NOTA AND SD2.D2_SERIE = SC6.C6_SERIE AND SD2.D_E_L_E_T_ = ''
 WHERE 
 --AND C6_NOTA = ''   
 --AND C5_EMISSAO BETWEEN (SELECT CONVERT(VARCHAR,CAST(GETDATE() - 180 AS DATE),112)) AND (SELECT CONVERT(VARCHAR,CAST(GETDATE() AS DATE),112)) 
  C5_EMISSAO BETWEEN  @DTINI AND @DTFIN
 AND C5_CLIENTE NOT IN ('002268' , '015699', '005286' )
 AND C6_PRODUTO <> 'VERBA'     
 AND C6_PRODUTO <> '1000.00.00001'                   
 AND C5_ZZTIPO IN ('N','F','X', 'L') 
 AND C6_BLQ <> 'R'
 AND B1_TIPO IN ('PA','RV') 
 AND C5.D_E_L_E_T_ = '' 

 UNION ALL

 SELECT	  'TP' = 'PV3',
          CASE C5_ZZTIPO 
				WHEN 'N' THEN 'NORMAL'
				WHEN 'F' THEN 'BONIFICACAO'
				WHEN 'X' THEN 'BONIFICACAO'
				WHEN 'L' THEN 'PALETE'
				ELSE ''  
			END               AS 'TIPO',
	     D2_COD AS 'COD.PRD', 
		 B1_DESC AS 'DESC', 
		 B1_ZZFAMIL AS 'FAM', 
		'FAMILIA'      = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z6' AND X5_CHAVE = B1_XFAMILI),
		'MARCA'        = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z8' AND X5_CHAVE = B1_XMARCA),
		'CATEGORIA'    = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z9' AND X5_CHAVE = B1_XCATEGO),
		'SUBCATEGORIA' = (SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = 'Z4' AND X5_CHAVE = B1_XSUBCAT),
          C6_PRODUTO          AS 'PRODUTO', 
          C6_DESCRI           AS 'DESCRICAO', 
		  B1_ZZFAMIL          AS 'FAMILIA', 
		  C5_NUM              AS 'NUM.PEDIDO', 
		  C5_ROMANEI          AS 'ROMANEIO',
		  D2_DOC            AS 'NF',
--		  C5_EMISSAO          AS 'EMISSAO', 
		  CAST(CONVERT (VARCHAR(10), C5_EMISSAO, 103) AS DATE) AS 'EMISSAO',
--          C5_FECENT           AS 'ENTREGA',
          CAST(CONVERT (VARCHAR(10), C5_FECENT, 103) AS DATE) AS 'ENTREGA',
		  C6_ITEM             AS 'ITEM', 
--		  C6_QTDVEN-C6_QTDENT AS 'SALDO',
		  C5_CLIENTE          AS 'COD.CLIENTE', 
		  A1_NOME             AS 'CLIENTE',
		  A1_ZZREDE           AS 'REDE',
		  A1_EST              AS 'ESTADO', 
		  A1_MUN              AS 'MUNICIPIO',
		  C5_VEND1            AS 'COD.VEND',     
		  A3_NOME             AS 'VENDEDOR',
		  A3_SUPER            AS 'COD.SUPER',  
		  'SUPERVISOR' = (SELECT A3_NOME FROM SA3010 WHERE A3_COD = (SELECT A3_SUPER FROM SA3010 WHERE A3_COD = A1_VEND AND D_E_L_E_T_ = '') AND D_E_L_E_T_ = ''), 
		  	'TP.FRETE.PV' = CASE A1_TPFRET  
			          WHEN 'C' THEN 'CIF'
					  WHEN 'F' THEN 'FOB'
                      ELSE ''
                     END, 
--		  C9_QTDLIB           AS 'RESERVA',
		  CASE C5_STAPED 
			WHEN 'S' THEN 'BLOQUEIO COMERCIAL'
			WHEN 'M' THEN 'MARGEM'
			WHEN 'C' THEN 'CREDITO'
			WHEN 'A' THEN 'AGENDAR'
			WHEN 'P' THEN 'PALETE'
			WHEN 'O' THEN 'OUTROS'
			WHEN 'R' THEN 'REJEITADO CREDITO'
			WHEN 'L' THEN 'ADM.PEDIDO'
			WHEN 'D' THEN 'LIB P/ GERAR ROM'
			WHEN 'T' THEN 'EM ROMANEIO'
			WHEN 'F' THEN 'FATURADO'
			ELSE ''
			END AS 'STATUS',
			A1_ZZROTA         AS 'ROTA',
		   (B1_PESO * C6_QTDVEN)   AS 'PESO.LIQUIDO',
		   (B1_PESBRU * C6_QTDVEN) AS 'PESO.BRUTO',
		    ZZQ_DESVEI AS 'TP.VEICULO',
			C5_ZZOBS1  AS 'OBS.PEDIDO',
		    A1_ZZOBSER AS 'OBS.SOBEL', 
		    A1_OBSERV  AS 'OBS.PROTHEUS',
			A1_REQAGEN AS 'REQ.AGENDA',
			--C5_DTAGEN  AS 'DT.AGENDAMENTO 1',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN, 103) AS DATE) AS 'DT.AGENDAMENTO 1',
		    C5_HRAGEN  AS 'HORA.AGENDAMENTO 1',
		   -- C5_DTAGEN1 AS 'DT.AGENDAMENTO 2',
		    CAST(CONVERT (VARCHAR(10), C5_DTAGEN1, 103) AS DATE) AS 'DT.AGENDAMENTO 2',
		    C5_HRAGEN2 AS 'HORA.AGENDAMENTO 2',		  
			--C5_DTAGEN2 AS 'DT.AGENDAMENTO 3',
			CAST(CONVERT (VARCHAR(10), C5_DTAGEN2, 103) AS DATE) AS 'DT.AGENDAMENTO 3',
		    C5_HRAGEN3 AS 'HORA.AGENDAMENTO 3',
			--C9_DTCARRE AS 'DT.CARREGAMENTO',
			CAST(CONVERT (VARCHAR(10), ZZQ_DTCARR, 103) AS DATE) AS 'DT.CARREGAMENTO',
			C5_TRANSP  AS 'TRANSP. ROMANEIO',
			'DESCRICAO. TRANSP.ROMANEIO' = ZZQ_DESTRA,
			'TIPO.VEICULO' = ZZQ_DESVEI,
			'TIPO.CARGA'   = IIF(ZZQ_TPCARG = '1', 'BATIDO', 'PALETIZADO'),
			'PRC.VENDA'    = C6_PRCVEN,
			'TP.FRETE.PV' = CASE C5_TPFRETE 
			                  WHEN 'C' THEN 'CIF'
							  WHEN 'F' THEN 'FOB'
                              ELSE ''
                             END, 
			'PED.CLIENTE'  = C5_ZZPEDCL,
			'HRA.ENTREGA'  = A1_ZZHORA,
			'LOJA.REDE'    = A1_ZZLOJA
 FROM SC5040 C5  
 LEFT JOIN SC6040 AS SC6 ON C6_NUM = C5_NUM AND C6_CLI = C5_CLIENT AND C6_LOJA = C5_LOJACLI AND SC6.D_E_L_E_T_ = ' '  
 LEFT JOIN SA1010 AS SA1 ON A1_COD = C5_CLIENT AND A1_LOJA = C5_LOJACLI AND SA1.D_E_L_E_T_ = ' '  
 LEFT JOIN SB1040 AS SB1 ON B1_COD = C6_PRODUTO AND SB1.D_E_L_E_T_ = ' '  
 LEFT JOIN SA3010 AS SA3 ON A3_COD = C5_VEND1 AND SA3.D_E_L_E_T_ = ' ' 
 LEFT JOIN SC9040 AS SC9 ON C9_PEDIDO = SC6.C6_NUM AND C9_ITEM = SC6.C6_ITEM AND C9_PRODUTO = SC6.C6_PRODUTO AND SC9.D_E_L_E_T_ = ' ' AND C9_BLEST 	= '' AND C9_BLCRED = ''  
 LEFT JOIN ZZQ010 AS ZZQ ON C5_ROMANEI = ZZQ_ROMANE AND ZZQ.D_E_L_E_T_ = ' ' 
 LEFT JOIN SD2040 AS SD2 ON SD2.D2_DOC = SC6.C6_NOTA AND SD2.D2_SERIE = SC6.C6_SERIE AND SD2.D_E_L_E_T_ = ''
 WHERE 
 --AND C6_NOTA = ''   
 --AND C5_EMISSAO BETWEEN (SELECT CONVERT(VARCHAR,CAST(GETDATE() - 180 AS DATE),112)) AND (SELECT CONVERT(VARCHAR,CAST(GETDATE() AS DATE),112)) 
  C5_EMISSAO BETWEEN  @DTINI AND @DTFIN
 AND C5_CLIENTE NOT IN ('002268' , '015699', '005286' )
 AND C6_PRODUTO <> 'VERBA'     
 AND C6_PRODUTO <> '1000.00.00001'                   
 AND C5_ZZTIPO IN ('N','F','X', 'L') 
 AND C6_BLQ <> 'R'
 AND B1_TIPO IN ('PA','RV') 
 AND C5.D_E_L_E_T_ = '' 