DECLARE @DTINI AS VARCHAR(8),
        @DTFIN AS VARCHAR(8)

SET @DTINI = '20210201'
SET @DTFIN = '20210201'
  
SELECT DISTINCT NRROM
FROM(
SELECT F2_ROMANEI AS NRROM
FROM SF2010 
WHERE F2_EMISSAO BETWEEN @DTINI AND @DTFIN
AND D_E_L_E_T_ = ''

UNION ALL

SELECT F2_ROMANEI AS NRROM
FROM SF2010 
WHERE F2_EMISSAO BETWEEN @DTINI AND @DTFIN

AND D_E_L_E_T_ = ''
UNION ALL

SELECT F2_ROMANEI AS NRROM
FROM SF2010 
WHERE F2_EMISSAO BETWEEN @DTINI AND @DTFIN
AND D_E_L_E_T_ = ''
) AS RES
WHERE NRROM <> ''
